const data1 = [
    {
      imgage: "https://cdn.muscleandstrength.com/sites/default/files/5_day_dumbbell_workout_-_1200x630.jpg",
      title: 'Dumbbell Only Workout:5 Day Dumbbell Workout Split',
      summary:'This 5 day dumbbell only workout program only requires dumbbells and is perfect for those looking to build lean muscle mass at home or on the go!',
      maingoal:'Build Muscle',
      type:'Split',
      level:'Intermediate',
      duration:'12 Weeks',
      perweek:'5',
      time:'45-60 minutes',
      equipment:'Bodyweight, Dumbbells',
      gender:'Male & Female',
      description1:"So, you’ve completed the 3 day full body dumbbell only workout?",
      description2:"AND you’ve completed the 4 day upper/lower dumbbell only workout as a form of progression?",
      description3:"Well, you’ve asked for it and today I’m bringing you the next step in our dumbbell only workout series.",
      description4:"The following workout, for those who only have access to a set of dumbbells, is a 5 day per week program.",
      description5:"It can be performed by those who work out at home in their home gym, travel frequently and need a go-to program they can do at a hotel gym, or anyone really who prefers to use dumbbells over other implements at the gym.",
      description6:"Recommended: Need help building muscle? Take our Free Muscle Building Course",
      stitle:'5 Day Dumbbell Workout Split Overview',
      split1:"The workout can be performed for up to 12 weeks.",
      split2:"After 12 weeks, you may want to consider increasing the volume within the workout, the weight of the dumbbells you are using, or look into facilities that offer more of a variety of weighted equipment.",
      split3:"The program calls for you to work out 5 days per week. What days you decide to work out on are completely up to you. Just ensure that you incorporate 2 rest/active recovery days into your weekly schedule.",
      split4:"The goal of the program is to help you build muscle. Of course, if you’d rather use it to help aid in fat loss, that is completely fine too. Just be sure to adjust your caloric intake accordingly.",
      split5:"Keep rest periods right around the 45 second mark for this workout program.",
      day1:"Day 1: Chest, Shoulders, & Triceps Dumbbell Workout",
      exercises: [
        { Exercise: 'Dumbbell Bench Press', Sets: 4, Reps: '8-10' },
        { Exercise: 'Incline Dumbbell Bench Press', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Floor Press', Sets: 3, Reps: '8-12' },
        { Exercise: 'Standing Dumbbell Press', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Lateral Raise', Sets: 3, Reps: '8-12' },
        { Exercise: 'Dumbbell Tricep Kickback', Sets: 3, Reps: '8-12' },
      ],
      day2:"Day 2: Legs & Core Dumbbell Workout",
      exercises1: [
        { Exercise: 'Dumbbell Goblet Squat', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Stiff Leg Deadlift', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Rear Lunge', Sets: 4, Reps: '8-10 Each' },
        { Exercise: 'Dumbbell Frog Squat', Sets: 3, Reps: '8-12' },
        { Exercise: 'Dumbbell Calf Raise', Sets: 4, Reps: '20' },
        { Exercise: 'Weighted Crunch', Sets: 3, Reps: '20' },
        { Exercise: 'Side Planks', Sets: 3, Reps: '20 Each' },
      ],
      day3:"Day 3: Back & Biceps Dumbbell Workout",
      exercises2: [
        { Exercise: 'Dumbbell Bent Over Row', Sets: 4, Reps: '8-12' },
        { Exercise: 'Tripod Dumbbell Row', Sets: 4, Reps: '8-12 Each' },
        { Exercise: 'Dumbbell Pullover', Sets: 3, Reps: '8-12' },
        { Exercise: 'Reverse Grip Dumbbell Row', Sets: 4, Reps: '8-12' },
        { Exercise: 'Dumbbell Bicep Curl', Sets: 3, Reps: '10-15' },
        { Exercise: 'Dumbbell Hammer Curl', Sets: 3, Reps: '10-15' },
      ],
      day4:"Day 4: Legs & Core Dumbbell Workout",
      exercises3: [
        { Exercise: 'Dumbbell Squat', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Deadlift', Sets: 4, Reps: '8-10' },
        { Exercise: 'Dumbbell Split Squat', Sets: 3, Reps: '8-12 Each' },
        { Exercise: 'Dumbbell Hip Thrust', Sets: 4, Reps: '10-15' },
        { Exercise: 'Dumbbell Calf Raise', Sets: 4, Reps: '20' },
        { Exercise: 'Dumbbell Side Bends', Sets: 3, Reps: '15 Each' },
        { Exercise: 'Plank', Sets: 3, Reps: '20 Secs' },
      ],
      day5:"Day 5: Complete Upper Body Dumbbell Workout",
      exercises4: [
        { Exercise: 'One Arm Dumbbell Rows', Sets: 4, Reps: '8-10 Each' },
        { Exercise: 'Dumbbell Arnold Press', Sets: 4, Reps: '8-10' },
        { Exercise: 'Incline Dumbbell Bench Press', Sets: 4, Reps: '8-12' },
        { Exercise: 'Chest Supported Dumbbell Row', Sets: 3, Reps: '8-12' },
        { Exercise: 'Dumbbell Pinwheel Curl', Sets: 2, Reps: '8-12' },
        { Exercise: 'Overhead Dumbbell Tricep Extension', Sets: 3, Reps: '8-12' },
        { Exercise: 'Dumbbell Shrug', Sets: 3, Reps: '12-15' },
      ],
    },
    {
      imgage: "https://cdn.muscleandstrength.com/sites/default/files/lean_woman_doing_dumbbell_row.jpg",
      title1: "3 Day Full Body Women's Dumbbell Only Workout",
      summary:'Transform yourself in as little as 45 minutes! This 8-week full body workout routine is designed for women who want to tone their bodies while growing their glutes.',
      maingoal:'Build Muscle',
      type:'Full Body',
      level:'Beginner',
      duration:'8 Weeks',
      perweek:'3',
      time:'45-60 minutes',
      equipment:'Bodyweight, Dumbbells',
      gender:'Male & Female',
      description1:"We believe that everyone can and should find some time to train and focus on self-improvement by working out. However, we understand that two of the biggest issues that women face are time to get to the gym and how to schedule that time for yourself.",
      description2:"We’ve previously shared dumbbell workouts that have five-day and four-day schedules, but we wanted to provide an option for those moms, wives, and ladies grinding through hard days that want to live the training life but are limited to training three times a week.",
      description3:"This program includes three workouts that you can perform each week, and no workout should take you longer than one hour with cardio included if that is something that is important to you. If you have a pair of dumbbells and open space in your home, then you can do this workout.",
      stitle:'About the Program',
      split1:"The workouts below are for weight training only. ",
      split2:"The only required equipment you need are dumbbells and bodyweight. The movements that would traditionally be performed on a flat bench can be performed on the floor.",
      split3:"If you have a bench and other equipment such as bands or a power tower that you want to add to this program, then feel free to do so with the same rep scheme as the exercises listed.",
      split4:"You will see that we devoted one day alone to the abs and glutes because these are two areas that we get the most questions and comments about from our female readers. ",
      split5:" We also made that day the first day on the schedule so you can target them right away and feel more confident about the program as you proceed. The other two days are a blend of lower and upper body days. We kept the exercises to a minimum for those who have busy schedules and want to get the job done as quickly as possible.",
      stitle2:"3 Day Full Body Women's Dumbbell Workout",
      day1:"Day 1 - Abs/Glutes",
      exercises: [
        { Exercise: 'Ab Crunch', Sets: 3, Reps: '15' },
        { Exercise: 'Lying Leg Raise', Sets: 3, Reps: '15' },
        { Exercise: 'Side Oblique Crunch (each side)', Sets: 3, Reps: '15 Each' },
        { Exercise: 'Glute Kick Back', Sets: 3, Reps: '15' },
        { Exercise: 'Dumbbell Romanian Deadlift', Sets: 3, Reps: '15' },
        { Exercise: 'Reverse Lunge', Sets: 3, Reps: '15' },
      ],
      day2:"Day 2 - Lower Body",
      exercises1: [
        { Exercise: 'Dumbbell Squat', Sets: 3, Reps: '15' },
        { Exercise: 'Dumbbell Lunge (each side)', Sets: 3, Reps: '15 Each' },
        { Exercise: 'Dumbbell Lying Leg Curl (on the floor)', Sets: 3, Reps: '15' },
        { Exercise: 'Bodyweight Single Leg Deadlift', Sets: 3, Reps: '15' },
        { Exercise: 'Seated Calf Raise', Sets: 3, Reps: '15' },
        { Exercise: 'Standing Calf Raise', Sets: 3, Reps: '15' }
      ],
      day3:"Day 3 - Upper Body",
      exercises2: [
        { Exercise: 'Dumbbell Bench Press (on the floor)', Sets: 3, Reps: '15' },
        { Exercise: 'Bent-Over Dumbbell Row', Sets: 3, Reps: '15' },
        { Exercise: 'Dumbbell Pullover', Sets: 3, Reps: '15' },
        { Exercise: 'Lateral Raise', Sets: 3, Reps: '15' },
        { Exercise: 'Hammer Dumbbell Curl', Sets: 3, Reps: '15' }
      ],
      day4:"Short On Time? No Problem!",
      summary1:"In a perfect world, you could create your schedule as you like and stick with it every day. We all know that nothing is perfect, and life happens. So, you may end up with only 15 minutes to train. Don’t consider it a loss and skip the workout. 15 minutes isn’t optimal, but it beats zero. This can be your “break glass in case of emergency” workout.",
      summary2:"Perform all the exercises for one set to absolute and total failure with weight that you can do for no more than 20 reps, and don’t stop until you’ve completed all the exercises for that workout. Do not use this as your normal training routine. It won’t be enough for a regular routine, but it can be helpful on that occasion if you need to do something over nothing.",
      summary3:"If we were to use Day 1 as an example, it would go like this. You can do the same method for Days 2 and 3.",
      exercises3: [
        { Exercise: 'Ab Crunch', Sets: 1, Reps: 'Failure' },
        { Exercise: 'Lying Leg Raise', Sets: 1, Reps: 'Failure' },
        { Exercise: 'Side Oblique Crunch (each side)', Sets: 1, Reps: 'Failure' },
        { Exercise: 'Glute Kick Back', Sets: 1, Reps: 'Failure' },
        { Exercise: 'Dumbbell Romanian Deadlift', Sets: 1, Reps: 'Failure' },
        { Exercise: 'Reverse Lunge', Sets: 1, Reps: 'Failure' }
      ],
      // day5:"Day 5: Complete Upper Body Dumbbell Workout",
      exercises4: [
        // { Exercise: 'One Arm Dumbbell Rows', Sets: 4, Reps: '8-10 Each' },
        // { Exercise: 'Dumbbell Arnold Press', Sets: 4, Reps: '8-10' },
        // { Exercise: 'Incline Dumbbell Bench Press', Sets: 4, Reps: '8-12' },
        // { Exercise: 'Chest Supported Dumbbell Row', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Pinwheel Curl', Sets: 2, Reps: '8-12' },
        // { Exercise: 'Overhead Dumbbell Tricep Extension', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Shrug', Sets: 3, Reps: '12-15' },
      ],
    },
    {
      imgage: "https://cdn.muscleandstrength.com/sites/default/files/4_day_maximum_mass_-_1200x630.jpg",
      title1: "4 Day Maximum Mass Workout",
      summary:'A mass building routine that features a great combination of effective compound and isolation movements along with intense, high impact five minute burn sets.',
      maingoal:'Build Muscle',
      type:'Split',
      level:'Intermediate',
      duration:'8 Weeks',
      perweek:'4',
      time:'45-60 minutes',
      equipment:'Barbell, Bodyweight, Dumbbells, Machines',
      gender:'Male & Female',
      description1:"Have experienced beginner gains and are confident they know how to build muscle.",
      description2:"Have a solid grasp of exercise form on the major compound movements.",
      description3:"Know how to set up an effective muscle building eating plan.",
      stitle:'About The 4 Day Workout',
      split1:"Overload is critical to the muscle building process. Push each set for the maximum number of reps, stopping that set either when you feel your form is slipping, or if you feel like you may fail on the next rep. Do not train to failure. The point is to stimulate growth, not annihilate your body and central nervous system.",
      split2:"Add weight to each exercise as frequently as possible, when it makes sense. I recommend using the same weight for every set of a given exercise, and when you are able to perform a comfortable number of reps on each set, add weight.",
      split3:"Rep ranges are simply a guideline. It's is ok to go over them, or a hair under at times. Again, the magic is overload. Rep ranges are simply a tool.",
      stitle2:"4 Day Maximum Mass Workout Split",
      day1:"Day 1 - Back & Biceps",
      exercises: [
        { Exercise: 'Deadlift', Sets: 2, Reps: '5' },
        { Exercise: 'One Arm Dumbbell Row', Sets: 3, Reps: '8-12' },
        { Exercise: 'Wide Grip Pull Up or Lat Pull Down', Sets: 3, Reps: '10-12' },
        { Exercise: 'Barbell Row', Sets: 3, Reps: '8-12' },
        { Exercise: 'Seated Cable Row or Machine Row', Sets: '5 Minutes', Reps: 'Burn' },
        { Exercise: 'EZ Bar Preacher Curl', Sets: 3, Reps: '10-12' },
        { Exercise: 'Concentration Curl', Sets: 3, Reps: '10-12' },
        { Exercise: 'Seated Dumbbell Curl', Sets: '5 Minutes', Reps: 'Burn' },
      ],
      day2:"Day 2 - Chest & Triceps",
      exercises1: [
        { Exercise: 'Bench Press', Sets: 3, Reps: '6-10' },
        { Exercise: 'Incline Dumbbell Bench Press', Sets: 3, Reps: '8-12' },
        { Exercise: 'Chest Dip', Sets: 3, Reps: 'AMRAP' },
        { Exercise: 'Cable Crossover or Pec Dec', Sets: 3, Reps: '12-15' },
        { Exercise: 'Machine Press or Dumbbell Bench Press', Sets: '5 Minutes', Reps: 'Burn' },
        { Exercise: 'EZ Bar Skullcrusher', Sets: 3, Reps: '8-12' },
        { Exercise: 'Two Arm Seated Dumbbell Extension', Sets: 3, Reps: '8-12' },
        { Exercise: 'Cable Tricep Extension', Sets: '5 Minutes', Reps: 'Burn' },
      ],
      day3:"Day 3 - Quads, Hamstrings, and Calves",
      exercises2: [
        { Exercise: 'Squat', Sets: 3, Reps: '6-10' },
        { Exercise: 'Leg Press', Sets: 3, Reps: '15-20' },
        { Exercise: 'Hack Squat or Dumbbell Lunge', Sets: 3, Reps: '8-12' },
        { Exercise: 'Leg Extension', Sets: '5 Minutes', Reps: 'Burn' },
        { Exercise: 'Stiff Leg Deadlift', Sets: 3, Reps: '8-12' },
        { Exercise: 'Leg Curl', Sets: '5 Minutes', Reps: 'Burn' },
        { Exercise: 'Standing Calf Raise', Sets: 3, Reps: '10-15' },
        { Exercise: 'Seated Calf Raise', Sets: '5 Minutes', Reps: 'Burn' },
      ],
      day4:"Day 4 - Shoulders, Traps, and Forearms",
      exercises3: [
        { Exercise: 'Seated Barbell Press', Sets: 3, Reps: '6-10' },
        { Exercise: 'Seated Arnold Press', Sets: 3, Reps: '8-12' },
        { Exercise: 'Dumbbell Lateral Raise', Sets: 3, Reps: '10-15' },
        { Exercise: 'Hammer Strength Press or Smith Press', Sets: '5 Minutes', Reps: 'Burn' },
        { Exercise: 'Upright Row', Sets: 3, Reps: '8-12' },
        { Exercise: 'Barbell Shrug or Dumbbell Shrug', Sets: '	5 Minutes', Reps: 'Burn' },
        { Exercise: 'Seated Barbell Wrist Curl', Sets: 3, Reps: '12-15' },
        { Exercise: 'Barbell Static Hold', Sets: '	5 Minutes', Reps: 'Burn' },
      ],
      notes:"Notes: Barbell Static Holds. Instead of performing reps you simply hold the bar as long as possible.",
      // day5:"Day 5: Complete Upper Body Dumbbell Workout",
      exercises4: [
        // { Exercise: 'One Arm Dumbbell Rows', Sets: 4, Reps: '8-10 Each' },
        // { Exercise: 'Dumbbell Arnold Press', Sets: 4, Reps: '8-10' },
        // { Exercise: 'Incline Dumbbell Bench Press', Sets: 4, Reps: '8-12' },
        // { Exercise: 'Chest Supported Dumbbell Row', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Pinwheel Curl', Sets: 2, Reps: '8-12' },
        // { Exercise: 'Overhead Dumbbell Tricep Extension', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Shrug', Sets: 3, Reps: '12-15' },
      ],
    },
    {
      imgage: "https://cdn.muscleandstrength.com/sites/default/files/phul_-_1200x630.jpg",
      title1: "Power Hypertrophy Upper Lower (P.H.U.L.) Workout",
      summary:'Build both size and strength in this 4 day split based around basic compound movements. Get the best of both worlds with bodybuilding and powerlifting.',
      maingoal:'Build Muscle',
      type:'Split',
      level:'Intermediate',
      duration:'12 Weeks',
      perweek:'4',
      time:'45-60 minutes',
      equipment:'Barbell, Dumbbells, Machines',
      gender:'Male & Female',
      description1:"The PHUL workout is based around the basic principles of strength and size.  This 4 day program will allow you to maximize results on both fronts in an easy adaptable routine built off the following principles:",
      description2:"Frequency. Studies have shown muscle protein synthesis (MPS) to be elevated for up to 48 hours after training. That would make it ideal for you to hit each muscle more frequently than a typical once per week split. The PHUL program is designed to hit each muscle group twice within a week.",
      description3:"Compounds. The PHUL program focuses on the big compound movements for optimal progression. While isolation movements are included in this program as well, the main goal is to increase performance on the main lifts, as well as pack on pounds of muscle.",
      description4:"Power. This program uses 2 of it's 4 working days to focus on pure strength training. The key to getting stronger and bigger is to utilize progressive overload and time under tension. These 2 days will see that you'll be able to use more weight on your hypertrophy days.",
      description5:"Hypertrophy. In addition to 2 power days, your other 2 days on the PHUL program will focus on hypertrophy (bodybuilding) style training. This way, not only will you be seeing strength increases but you'll be building size as well.",
      stitle:'PHUL Workout Schedule:',
      split1:"Day 1: Upper Power",
      split2:"Day 2: Lower Power",
      split3:"Day 3: Off",
      split4:"Day 4: Upper Hypertrophy",
      split5:"Day 5: Lower Hypertrophy",
      split6:"Day 6: Off",
      split7:"Day 7: Off",
      day1:"Day 1 - Upper Power",
      exercises: [
        { Exercise: 'Barbell Bench Press', Sets: '3-4', Reps: '3-5' },
        { Exercise: 'Incline Dumbbell Bench Press', Sets: '3-4', Reps: '6-10' },
        { Exercise: 'Bent Over Row', Sets: '3-4', Reps: '3-5' },
        { Exercise: 'Lat Pull Down', Sets: '3-4', Reps: '6-10' },
        { Exercise: 'Overhead Press', Sets: '2-3', Reps: '5-8' },
        { Exercise: 'Barbell Curl', Sets: '2-3', Reps: '6-10' },
        { Exercise: 'Skullcrusher', Sets: '2-3', Reps: '6-10' },
      ],
      day2:"Day 2 - Lower Power",
      exercises1: [
        { Exercise: 'Squat', Sets: '3-4', Reps: '3-5' },
        { Exercise: 'Deadlift', Sets: '3-4', Reps: '3-5' },
        { Exercise: 'Leg Press', Sets: '3-5', Reps: '10-15' },
        { Exercise: 'Leg Curl', Sets: '3-4', Reps: '6-10' },
        { Exercise: 'Calf Exercise', Sets: '4', Reps: '6-10' },
      ],
      day3:"Day 4 - Upper Hypertrophy",
      exercises2: [
        { Exercise: 'Incline Barbell Bench Press', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Flat Bench Dumbbell Flye', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Seated Cable Row', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'One Arm Dumbbell Row', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Dumbbell Lateral Raise', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Seated Incline Dumbbell Curl', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Cable Tricep Extension', Sets: '3-4', Reps: '8-12' },
      ],
      day4:"Day 5 - Lower Hypertrophy",
      exercises3: [
        { Exercise: 'Front Squat', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Barbell Lunge', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Leg Extension', Sets: '3-4', Reps: '10-15' },
        { Exercise: 'Leg Curl', Sets: '3-4', Reps: '10-15' },
        { Exercise: 'Upright Row', Sets: 3, Reps: '8-12' },
        { Exercise: 'Seated Calf Raise', Sets: '3-4', Reps: '8-12' },
        { Exercise: 'Calf Press', Sets: '3-4', Reps: '8-12' },
      ],
      // notes:"Notes: Barbell Static Holds. Instead of performing reps you simply hold the bar as long as possible.",
      // day5:"Day 5: Complete Upper Body Dumbbell Workout",
      exercises4: [
        // { Exercise: 'One Arm Dumbbell Rows', Sets: 4, Reps: '8-10 Each' },
        // { Exercise: 'Dumbbell Arnold Press', Sets: 4, Reps: '8-10' },
        // { Exercise: 'Incline Dumbbell Bench Press', Sets: 4, Reps: '8-12' },
        // { Exercise: 'Chest Supported Dumbbell Row', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Pinwheel Curl', Sets: 2, Reps: '8-12' },
        // { Exercise: 'Overhead Dumbbell Tricep Extension', Sets: 3, Reps: '8-12' },
        // { Exercise: 'Dumbbell Shrug', Sets: 3, Reps: '12-15' },
      ],
    }
    
  ]
  export default data1;